services:
  transaction-db:
    image: postgres:15-alpine
    container_name: transaction-db
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - transaction-data:/var/lib/postgresql/data
    networks:
      - app-network

  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ledger-transaction-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transaction-db:5432/transactiondb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - transaction-db
    networks:
      - app-network

networks:
  app-network:
    name: microservices-network
    driver: bridge

volumes:
  transaction-data:

#
#    mvn clean package
#    # Navigate to project root (where docker-compose.yml is)
#    cd /path/to/project-root
#
#    # Build and start all services
#    docker-compose up --build
#
#    # Or run in detached mode (background)
#    docker-compose up --build -d
#
#    # View logs
#    docker-compose logs -f
#
#    # View logs for specific service
#    docker-compose logs -f transaction-service
#    docker-compose logs -f dispute-service